### ISSUE TITLE
Movie DB Enpoints

### ISSUE THREAD

**Issue by benistta** [wesatt/consultancy_the_list_fe#8]
- [x] Movie search by title. 
- [x] Movie lookup by id.
- [x] Movie top_rated.
- [x] Movie PORO created and has (at a minimum) [:id, :title, :overview] 
- [x] Controller follow good RESTful convention when necessary.

**Comment by wesatt** [comment]
I changed some of the items for this story to meet our expectations a little closer.

I'd like some input as to which attributes we want our PORO to have.

**Comment by benistta** [comment]
Thank you Wes for doing that.  My thinking is that for the PORO we would probably need id,  title, and the overview or summary and maybe a poster if we want to include that. What do you think?
This ticket was written when we did not have a very clear idea of what we needed specifically. We could change it to meet our expectations now. Thank you!
