### ISSUE TITLE
Good Reads Endpoints

### ISSUE THREAD

**Issue by benistta** [wesatt/consultancy_the_list_fe#9]
- [ ] All endpoints should be fully tested for happy path AND sad path. 
- [x] All endpoints will expect to return JSON data only
- [ ] API will be compliant to the [JSON API spec] and match requirements 
- [ ] Controller follow good RESTful convention when necessary.

**Comment by SaiHall** [comment]
Good reads fell through, using open library instead

**Comment by SaiHall** [comment]
Open Library also fell through. Using Google books api instead
